[build]
  command = "npm run build"
  publish = ".next"
  functions = ".next/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"  # Updated to Node 20 for better Next.js 15 support
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_OPTIONS = "--max_old_space_size=4096"  # Increase memory for build

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@supabase/supabase-js"]

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  framework = "next"
